### ISSUE TITLE
Can not run the sample on hololens

### ISSUE THREAD

**Issue by hannahchu** [qian256/HoloLensARToolKit#14]
Hi,
     I've deployed the sample with scene HoloLensARToolKitCube onto hololens, but when I open the app,  it crashes after showing the "HoloLensARToolKit Sample scene" title. ( I'm using Unity 5.6.1f1 and visual studio2017) 
    Any idea about what causes the crash and any suggestion to fix it ?
    Thank you so much!!!

**Comment by qian256** [comment]
What version of Win10 is on HoloLens? Could you double-check that the capabilities of app are correctly configured, e.g. webcam? When you deploy the app from Visual Studio, is there any useful debugging output that can help trace the problem?

**Comment by hannahchu** [comment]
It works after I update Hololens to 10.0.14393.1198! Thank you so much!!

**Comment by qian256** [comment]
Good to hear!
