### ISSUE TITLE
Own Markers (No Issue)

### ISSUE THREAD

**Issue by Masi5192** [qian256/HoloLensARToolKit#15]
Can you tell me how to use my own Markers?
I am new in developing on the Hololens and need some help.
Thanks.

**Comment by qian256** [comment]
What kind of markers do you want to use?
For markers like Hiro and Kanji, you can create that of your own following this post: https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training
After that, you can look at HoloLensARToolKitSingle sample scene, and basically replace the Hiro with your own.
