### ISSUE TITLE
printable pattern for cube

### ISSUE THREAD

**Issue by khcy82dyc** [qian256/HoloLensARToolKit#20]
Hi, I'm running the cube sample and I've made a printed cube using 'cube00-05-hamming63-a4.pdf'
When I run the example it only track on of the pattern and does not recognise the rest. could you upload a pdf file that you used to print and make your cube shown in the example?
Thanks!

**Comment by qian256** [comment]
Hi @khcy82dyc , the cube that I used in the sample project is here: 
[https://github.com/artoolkit/artoolkit5/blob/master/doc/patterns/Cubes/cube00-05-letter.pdf](https://github.com/artoolkit/artoolkit5/blob/master/doc/patterns/Cubes/cube00-05-letter.pdf)
