### ISSUE TITLE
Compatibility with Unity2017.1 (question)

### ISSUE THREAD

**Issue by tsteffelbauer** [qian256/HoloLensARToolKit#21]
Hi,

has someone checked the compatibility with Unity2017.1 and does it work?

**Comment by qian256** [comment]
I haven't tested. I'd like to know as well.

**Comment by ericalbers** [comment]
I have just run it in 2017.1.0b7 personal, tracks well.

**Comment by qian256** [comment]
Thanks @ericalbers
