### ISSUE TITLE
No video stream and 3d objects during live preview from Device Portal

### ISSUE THREAD

**Issue by PiotrKlys** [qian256/HoloLensARToolKit#31]
Hello,

I have a problem with your sample during live preview from Device Portal (Mixed Reality Capture) - I do not get any video and 3d objects. Are you familiar with that issue? Maybe there is something that I should configure additionally?

Best regards,
Piotr

**Comment by PiotrKlys** [comment]
Ok. In my case I would like to see just in "real time" what hololens user is seeing, so option with recording is not good enough. Do you see any other way to solve that issue?

**Comment by qian256** [comment]
I don't aware of other solutions.
