### ISSUE TITLE
Retest compatibility and update README?

### ISSUE THREAD

**Issue by DanAndersen** [qian256/HoloLensARToolKit#36]
Hi,
I am trying to ensure I have identical development conditions from when you determined your compatibility in your README:

1. Unity 5.6.0f3
2. Visual Studio 2017 (Toolset v141)
3. ARToolKit 5.3.2
4. Windows 10 SDK 10.0.10240.0 to 10.0.14393.0

However, when VS2017.2 changed to VS2017.3, there was an incompatibility that was introducted when targeting UWP projects using .NET. See [here](https://forum.unity.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/) for details. A fix was apparently introduced into Unity with 5.6.3.

However, what this means is that if a user tries to use the latest version of VS2017 (note that old versions of VS2017, e.g. VS2017.2, are not made available by Microsoft anymore -- it's a forced upgrade), they will not be able to build the HoloLensARToolKit samples with Unity 5.6.0f3.

I was wondering if you would be able to rerun your code on an updated development environment and determine the current version of Unity and VS2017 that a successful test has been run on.

**Comment by DanAndersen** [comment]
Hi,
I haven't encountered that (though I'm using Unity 2018.2 now). It sounds like it's trying to go into the video recording mode (forcing it to 30fps) but I have not been having that issue, at least in my fork of the code I've been using.

**Comment by qian256** [comment]
What HoloLens OS version are you using? When I open the camera in video mode, it pops up. That is a very annoying effect. I tried with boh ARUWPVideo and [HoloLensCameraStream](https://github.com/VulcanTechnologies/HoloLensCameraStream). They all have the same results.

**Comment by qian256** [comment]
It turns out to be Unity version problem. 2017 LTS has the problem but 2018 non-LTS version is fine.
