### ISSUE TITLE
Referencing main camera with via tag instead of name

### ISSUE THREAD

**Issue by frankotastico** [qian256/HoloLensARToolKit#41]
Instead of finding the main camera via name I'd suggest finding it via Tag
holoLensCamera = GameObject.FindWithTag("MainCamera");
Seems like a better practice to me as it's default and grants out of the box compatiblity with the HoloToolkit and own naming conventions.

**Comment by qian256** [comment]
Merged. I will test and push to the grayscale branch as well. Thanks.
