### ISSUE TITLE
Does this toolkit work with a cylindrical object?

### ISSUE THREAD

**Issue by khadkaboy** [qian256/HoloLensARToolKit#45]
Does this toolkit work with a cylindrical object?

**Comment by qian256** [comment]
Nope. This is a limitation of ARToolKit

**Comment by khadkaboy** [comment]
Do you have any suggestion regarding tracking cylindrical objects?

**Comment by qian256** [comment]
You can look at Vuforia library, https://library.vuforia.com/articles/Solution/Cylinder-Targets-Guide
