### ISSUE TITLE
Front camera cannot get work

### ISSUE THREAD

**Issue by mudusun** [qian256/HoloLensARToolKit#6]
when I rebuild the scene in my own project, why the camera cannot get work? I made every setting as same as it was done in this project. There is no error in deploy but the camera indicator was not on when running the solution. There are no other access package except HoloToolkit and ARToolKitUWP.unitypackage. Can you help me with this? 

![image](https://cloud.githubusercontent.com/assets/17498734/23682824/f9bca496-0395-11e7-85a1-7e5a5a4c01a2.png)

**Comment by qian256** [comment]
Not sure what the problem is. Have you solved it?

**Comment by mudusun** [comment]
Not yet. Still working on it. And I have no clue...

**Comment by jdcart** [comment]
Did you make sure you have the WebCam capability on? 

Player Settings > Windows Store > Publishing Settings > Capabilities

**Comment by mudusun** [comment]
Yes,  the WebCam capability is on. I guess that there should have some connection with ARToolKitUWP folder in the project?

**Comment by qian256** [comment]
No, the ARToolKitUWP folder builds the dynamic link library `ARToolKitUWP.dll`, and it is already in the Unity project under `Plugins/`
