### ISSUE TITLE
A problem with files .dat?

### ISSUE THREAD

**Issue by NawelNima** [qian256/HoloLensARToolKit#7]
Hello, I tried to change the .dat files of the project with mine, but it does not seem to work. The .meta files are not recreating. 
Can someone help me please?

**Comment by qian256** [comment]
Which dat file? camera calibration or multi-marker configuration?

**Comment by NawelNima** [comment]
About multi-marker configuration, when I changed them, nothing happens. As if they were not taken into account.

**Comment by qian256** [comment]
Are you modifying one of the example? Could you please send me the configuration file you changed, and the screenshot of you ARUWPController and ARUWPMarker options in Unity?

**Comment by qian256** [comment]
Hi @NawelNima , did you fix the problem yet?

**Comment by NawelNima** [comment]
Hello, not yet. 
I tried to change the data (the postions) in cube.dat or multi-barcode-4x3.dat. But like I said before, nothing changes, the markers in the scene remain at the same place.

**Comment by qian256** [comment]
The meta file is still no creating? Have you tried the recent commit, where the marker configuration is same as ARToolKit.

**Comment by tsteffelbauer** [comment]
Try to reload the marker by temporarily changing to a different marker and then switching back
